rm -r ./nrel5mw/*.chkp
rm -r ./nrel5mw/*.outb
rm -r ./nrel5mw/*.out
rm -r ./nrel5mw/*.sum
rm -r ./nrel5mw/*.ech
rm -r ./nrel5mw/vtk
rm -r ./*.h5
rm -r ./*.bak
rm -r ./turbineAlloc.0.txt
rm -r ./precice-profiling
rm -r ../precice-run
